"""Add period locking and document extra_metadata

Revision ID: d6282968e2a4
Revises: 0f391613fa95
Create Date: 2025-12-18 15:14:34.220304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6282968e2a4'
down_revision: Union[str, None] = '0f391613fa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('period_locked_until', sa.DateTime(), nullable=True))
    op.add_column('document_versions', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('extra_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extra_metadata')
    op.drop_column('document_versions', 'extra_metadata')
    op.drop_column('companies', 'period_locked_until')
    # ### end Alembic commands ###
